_default:
    @just --list

clean:
    rm -rf verilator_build
    rm -f yosys_*.log
    rm -f vivad*.{jou,log}

verilator-test:
    verilator --binary --timing --trace-fst -Wno-lint \
        --Mdir verilator_build \
        -j `nproc` \
        --top tb \
        ../lzc.sv tb.sv lzc_prior.sv
    cd verilator_build && ./Vtb && cd ..

yosys-synth:
    yosys -p 'prep -top lzc' ../lzc.sv | tee yosys_recursive.log # Should succeed
    yosys -p 'prep -top lzc_prior' lzc_prior.sv | tee yosys_prior.log # Should error

quartus-synth:
    @echo "todo: synth with quartus prime lite"

dc-synth:
    @echo "todo: synth with design compiler"

vivado-synth:
    vivado -mode batch -source vivado_recursive.tcl | tee vivado_recursive.log
    vivado -mode batch -source vivado_prior.tcl | tee vivado_prior.log

all-synth:
    @just clean
    @just yosys-synth
    @just quartus-synth
    @just dc-synth
    @just vivado-synth
